/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ro.ubbcluj2013.dataUi;

import ro.ubbcluj2013.dataUi.controller.InsertDialogController;
import ro.ubbcluj2013.dataUi.controller.DataController;
import de.unikassel.cs.kde.trias.model.Triple;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import ro.ubbcluj2013.dataUi.util.ExcelFiltering;
/**
 *
 * @author Fluffy
 */
public class DataFrame extends javax.swing.JFrame {

    /**
     * Creates new form DataFrame
     */
    public DataFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertDialog = new javax.swing.JDialog();
        okInsertButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        objectsTab = new javax.swing.JPanel();
        newObjField = new javax.swing.JTextField();
        newObjLabel = new javax.swing.JLabel();
        addObjButton = new javax.swing.JButton();
        objListLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        objList = new javax.swing.JList();
        deleteObjButton = new javax.swing.JButton();
        clearObjButton = new javax.swing.JButton();
        attributesTab = new javax.swing.JPanel();
        newAttrField = new javax.swing.JTextField();
        newAttrLabel = new javax.swing.JLabel();
        addAttrButton = new javax.swing.JButton();
        attrListLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        attrList = new javax.swing.JList();
        deleteAttrButton = new javax.swing.JButton();
        clearAttrButton = new javax.swing.JButton();
        conditionsTab = new javax.swing.JPanel();
        newCondField = new javax.swing.JTextField();
        newCondLabel = new javax.swing.JLabel();
        addCondButton = new javax.swing.JButton();
        condListLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        condList = new javax.swing.JList();
        deleteCondButton = new javax.swing.JButton();
        clearCondButton = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();
        errorDialog = new javax.swing.JDialog();
        errorMessage = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        conditionLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editCompMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        InsertDialog.setTitle("Insert Data");
        InsertDialog.setMinimumSize(new java.awt.Dimension(500, 350));

        okInsertButton.setText("OK");
        okInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okInsertButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(325, 270));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(325, 270));

        newObjField.setMaximumSize(new java.awt.Dimension(154, 20));
        newObjField.setMinimumSize(new java.awt.Dimension(154, 20));
        newObjField.setPreferredSize(new java.awt.Dimension(154, 20));

        newObjLabel.setText("New Object:");

        addObjButton.setText("Add");
        addObjButton.setMaximumSize(new java.awt.Dimension(63, 23));
        addObjButton.setMinimumSize(new java.awt.Dimension(63, 23));
        addObjButton.setPreferredSize(new java.awt.Dimension(63, 23));
        addObjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObjButtonActionPerformed(evt);
            }
        });

        objListLabel.setText("List of Objects:");

        objList.setMaximumSize(new java.awt.Dimension(202, 222));
        objList.setMinimumSize(new java.awt.Dimension(202, 222));
        objList.setPreferredSize(new java.awt.Dimension(202, 222));
        jScrollPane2.setViewportView(objList);

        deleteObjButton.setText("Delete");
        deleteObjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteObjButtonActionPerformed(evt);
            }
        });

        clearObjButton.setText("Clear");
        clearObjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearObjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout objectsTabLayout = new javax.swing.GroupLayout(objectsTab);
        objectsTab.setLayout(objectsTabLayout);
        objectsTabLayout.setHorizontalGroup(
            objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objectsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, objectsTabLayout.createSequentialGroup()
                        .addGroup(objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(deleteObjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearObjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(objectsTabLayout.createSequentialGroup()
                                .addComponent(newObjField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addObjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(objectsTabLayout.createSequentialGroup()
                        .addComponent(newObjLabel)
                        .addGap(97, 97, 97)))
                .addGroup(objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(objectsTabLayout.createSequentialGroup()
                        .addComponent(objListLabel)
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        objectsTabLayout.setVerticalGroup(
            objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(objectsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newObjLabel)
                    .addComponent(objListLabel))
                .addGap(13, 13, 13)
                .addGroup(objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(objectsTabLayout.createSequentialGroup()
                        .addGroup(objectsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addObjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newObjField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteObjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearObjButton)
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Objects", objectsTab);

        newAttrField.setMaximumSize(new java.awt.Dimension(154, 20));
        newAttrField.setMinimumSize(new java.awt.Dimension(154, 20));
        newAttrField.setPreferredSize(new java.awt.Dimension(154, 20));

        newAttrLabel.setText("New Attribut:");

        addAttrButton.setText("Add");
        addAttrButton.setMaximumSize(new java.awt.Dimension(63, 23));
        addAttrButton.setMinimumSize(new java.awt.Dimension(63, 23));
        addAttrButton.setPreferredSize(new java.awt.Dimension(63, 23));
        addAttrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttrButtonActionPerformed(evt);
            }
        });

        attrListLabel.setText("List of Attributs:");

        attrList.setMaximumSize(new java.awt.Dimension(202, 222));
        attrList.setMinimumSize(new java.awt.Dimension(202, 222));
        attrList.setPreferredSize(new java.awt.Dimension(202, 222));
        jScrollPane3.setViewportView(attrList);

        deleteAttrButton.setText("Delete");
        deleteAttrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAttrButtonActionPerformed(evt);
            }
        });

        clearAttrButton.setText("Clear");
        clearAttrButton.setMaximumSize(new java.awt.Dimension(63, 23));
        clearAttrButton.setMinimumSize(new java.awt.Dimension(63, 23));
        clearAttrButton.setPreferredSize(new java.awt.Dimension(63, 23));
        clearAttrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAttrButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout attributesTabLayout = new javax.swing.GroupLayout(attributesTab);
        attributesTab.setLayout(attributesTabLayout);
        attributesTabLayout.setHorizontalGroup(
            attributesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributesTabLayout.createSequentialGroup()
                .addGroup(attributesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attributesTabLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(attributesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteAttrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(attributesTabLayout.createSequentialGroup()
                                .addComponent(newAttrField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addAttrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clearAttrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(attributesTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newAttrLabel)
                        .addGap(188, 188, 188)))
                .addGroup(attributesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attributesTabLayout.createSequentialGroup()
                        .addComponent(attrListLabel)
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        attributesTabLayout.setVerticalGroup(
            attributesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attributesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newAttrLabel)
                    .addComponent(attrListLabel))
                .addGap(13, 13, 13)
                .addGroup(attributesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(attributesTabLayout.createSequentialGroup()
                        .addGroup(attributesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newAttrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addAttrButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteAttrButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearAttrButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Attributes", attributesTab);

        newCondField.setMaximumSize(new java.awt.Dimension(154, 20));
        newCondField.setMinimumSize(new java.awt.Dimension(154, 20));
        newCondField.setPreferredSize(new java.awt.Dimension(154, 20));

        newCondLabel.setText("New Condition:");

        addCondButton.setText("Add");
        addCondButton.setMaximumSize(new java.awt.Dimension(63, 23));
        addCondButton.setMinimumSize(new java.awt.Dimension(63, 23));
        addCondButton.setPreferredSize(new java.awt.Dimension(63, 23));
        addCondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCondButtonActionPerformed(evt);
            }
        });

        condListLabel.setText("List of Conditions:");

        condList.setMaximumSize(new java.awt.Dimension(202, 222));
        condList.setMinimumSize(new java.awt.Dimension(202, 222));
        condList.setPreferredSize(new java.awt.Dimension(202, 222));
        jScrollPane4.setViewportView(condList);

        deleteCondButton.setText("Delete");
        deleteCondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCondButtonActionPerformed(evt);
            }
        });

        clearCondButton.setText("Clear");
        clearCondButton.setMaximumSize(new java.awt.Dimension(63, 23));
        clearCondButton.setMinimumSize(new java.awt.Dimension(63, 23));
        clearCondButton.setPreferredSize(new java.awt.Dimension(63, 23));
        clearCondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCondButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conditionsTabLayout = new javax.swing.GroupLayout(conditionsTab);
        conditionsTab.setLayout(conditionsTabLayout);
        conditionsTabLayout.setHorizontalGroup(
            conditionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conditionsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conditionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conditionsTabLayout.createSequentialGroup()
                        .addComponent(newCondLabel)
                        .addGap(97, 97, 97))
                    .addGroup(conditionsTabLayout.createSequentialGroup()
                        .addComponent(newCondField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(conditionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearCondButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteCondButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCondButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(conditionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conditionsTabLayout.createSequentialGroup()
                        .addComponent(condListLabel)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        conditionsTabLayout.setVerticalGroup(
            conditionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conditionsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conditionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCondLabel)
                    .addComponent(condListLabel))
                .addGap(13, 13, 13)
                .addGroup(conditionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conditionsTabLayout.createSequentialGroup()
                        .addGroup(conditionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newCondField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCondButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteCondButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearCondButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Conditions", conditionsTab);

        javax.swing.GroupLayout InsertDialogLayout = new javax.swing.GroupLayout(InsertDialog.getContentPane());
        InsertDialog.getContentPane().setLayout(InsertDialogLayout);
        InsertDialogLayout.setHorizontalGroup(
            InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertDialogLayout.createSequentialGroup()
                        .addGap(0, 410, Short.MAX_VALUE)
                        .addComponent(okInsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        InsertDialogLayout.setVerticalGroup(
            InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okInsertButton)
                .addContainerGap())
        );

        fileChooser.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        fileChooser.setCurrentDirectory(new java.io.File("C:\\Users"));
        fileChooser.setDialogTitle("Choose file");

        errorMessage.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage.setMaximumSize(new java.awt.Dimension(300, 100));
        errorMessage.setMinimumSize(new java.awt.Dimension(300, 100));
        errorMessage.setPreferredSize(new java.awt.Dimension(300, 100));

        closeButton.setText("OK");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("OK");
        confirmButton.setEnabled(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manual Input");
        setMaximumSize(new java.awt.Dimension(915, 600));
        setMinimumSize(new java.awt.Dimension(915, 600));

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(700, 450));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(700, 450));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setOpaque(false);
        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        conditionLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        conditionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conditionLabel.setAlignmentX(0.5F);
        conditionLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Condition", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        conditionLabel.setMaximumSize(new java.awt.Dimension(700, 50));
        conditionLabel.setMinimumSize(new java.awt.Dimension(700, 50));
        conditionLabel.setPreferredSize(new java.awt.Dimension(700, 50));

        nextButton.setText("Next -->");
        nextButton.setEnabled(false);
        nextButton.setMaximumSize(new java.awt.Dimension(150, 35));
        nextButton.setMinimumSize(new java.awt.Dimension(150, 35));
        nextButton.setPreferredSize(new java.awt.Dimension(150, 35));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("<-- Previous");
        previousButton.setEnabled(false);
        previousButton.setMaximumSize(new java.awt.Dimension(150, 35));
        previousButton.setMinimumSize(new java.awt.Dimension(150, 35));
        previousButton.setPreferredSize(new java.awt.Dimension(150, 35));
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.setEnabled(false);
        finishButton.setMaximumSize(new java.awt.Dimension(150, 35));
        finishButton.setMinimumSize(new java.awt.Dimension(150, 35));
        finishButton.setPreferredSize(new java.awt.Dimension(150, 35));
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        editCompMenuItem.setMnemonic('t');
        editCompMenuItem.setText("Edit Components");
        editCompMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCompMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(editCompMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conditionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(finishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conditionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Other initializations
    DefaultListModel olm = new DefaultListModel(), alm = new DefaultListModel(), clm = new DefaultListModel();
    InsertDialogController idc = new InsertDialogController();
    DataController dc = new DataController();
    int condIndex;
    
    private javax.swing.JTable jTable1;
    
    //Main menu items
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        
        //new .xls filter
        ExcelFiltering filter = new ExcelFiltering();
        fileChooser.setFileFilter(filter);
        
        //Open Dialog to choose a file to open
        int returnVal = fileChooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();            
                System.out.println("File: " + file.getName() + ".");    
            } else {
                System.out.println("Open command cancelled by user.");
            }       
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        // TODO add your handling code here:
        if (!(olm.size()>0)){
            InsertDialog.pack();
            InsertDialog.setVisible(true);
        
            //InsertDialog initialize
            objList.setModel(olm);
            attrList.setModel(alm);
            condList.setModel(clm);
        }else{
            errorDialog.setTitle("New Input");
            errorMessage.setText("Are you sure you want to delete the previous data?");
            errorDialog.setVisible(true);
            closeButton.setText("CANCEL");
            confirmButton.setVisible(true);
            confirmButton.setEnabled(true);
            errorDialog.pack();
        }
      
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void editCompMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCompMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCompMenuItemActionPerformed

    
    
    /**
     * InsertDialog okButton
     */
    private void okInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okInsertButtonActionPerformed
        // TODO add your handling code here:
        if (olm.size()>0){
            if (alm.size()>0){
                if (clm.size()>0){
                    ArrayList<String> listObj = new ArrayList<String>();
                    for (int i=0;i<olm.size();i++){
                        listObj.add(olm.get(i).toString());            
                    }

                    ArrayList<String> listAttr = new ArrayList<String>();
                    for (int i=0;i<alm.size();i++){
                        listAttr.add(alm.get(i).toString());            
                    }

                    ArrayList<String> listCond = new ArrayList<String>();
                    for (int i=0;i<clm.size();i++){
                        listCond.add(clm.get(i).toString());            
                    }

                    dc.collectLists(listObj, listAttr, listCond);
                    dc.generateListOfTriples();

                    InsertDialog.dispose();        

                    condIndex =0;
                    conditionLabel.setText(clm.get(condIndex).toString()); 
                    jTable1 = dc.getTable(condIndex);
                    jScrollPane1.setViewportView(jTable1);
                    
                    if (clm.size()>1){
                        nextButton.setEnabled(true);                        
                    } else {
                        finishButton.setEnabled(true);
                    }           
                    
                
                } else{
                    confirmButton.setVisible(false);
                    errorDialog.setTitle("Error");
                    errorMessage.setText("At least one condition must be introduced!");
                    errorDialog.setVisible(true);
                    errorDialog.pack();
                    
                }                
            }else{  
               confirmButton.setVisible(false); 
               errorDialog.setTitle("Error");
               errorMessage.setText("At least one attribute must be introduced!");
               errorDialog.setVisible(true);
               errorDialog.pack();
            }
        }else{            
           confirmButton.setVisible(false); 
           errorDialog.setTitle("Error");
           errorMessage.setText("At least one object must be introduced!");
           errorDialog.setVisible(true);
           errorDialog.pack();
           confirmButton.setVisible(false);
        }

        
    }//GEN-LAST:event_okInsertButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        dc.collectTableInfo(jTable1, condIndex);
        condIndex++;
        conditionLabel.setText(clm.get(condIndex).toString());
        
        jTable1 = dc.getTable(condIndex);
        jScrollPane1.setViewportView(jTable1);

        previousButton.setEnabled(true);
        if (condIndex == clm.size()-1){
            nextButton.setEnabled(false);
            finishButton.setEnabled(true);
        } 
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void addAttrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttrButtonActionPerformed
        // TODO add your handling code here:
        String text = newAttrField.getText();
        if (!text.isEmpty()){            
            newAttrField.setText("");
            idc.addToListModel(text, alm);
        }else{                           
           errorDialog.setTitle("Error");
           errorMessage.setText("No text introuced!");
           errorDialog.setVisible(true);
           errorDialog.pack();
        }        
    }//GEN-LAST:event_addAttrButtonActionPerformed

    private void addObjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObjButtonActionPerformed
        // TODO add your handling code here:
        String text = newObjField.getText();
        if (!text.isEmpty()){            
            newObjField.setText("");
            idc.addToListModel(text, olm);
        }else{                           
           errorDialog.setTitle("Error");
           errorMessage.setText("No text introuced!");
           errorDialog.setVisible(true);
           errorDialog.pack();
        }      
    }//GEN-LAST:event_addObjButtonActionPerformed

    private void deleteObjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteObjButtonActionPerformed
        // TODO add your handling code here:
        int n = objList.getSelectedIndex();        
        idc.deleteFromListModel(n, olm);
    }//GEN-LAST:event_deleteObjButtonActionPerformed

    private void clearObjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearObjButtonActionPerformed
        // TODO add your handling code here:
        idc.clearListModel(olm);
    }//GEN-LAST:event_clearObjButtonActionPerformed

    private void deleteAttrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAttrButtonActionPerformed
        // TODO add your handling code here:
        int n = attrList.getSelectedIndex();        
        idc.deleteFromListModel(n, alm);
    }//GEN-LAST:event_deleteAttrButtonActionPerformed

    private void clearAttrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAttrButtonActionPerformed
        // TODO add your handling code here:
        idc.clearListModel(alm);
    }//GEN-LAST:event_clearAttrButtonActionPerformed

    private void deleteCondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCondButtonActionPerformed
        // TODO add your handling code here:
        int n = condList.getSelectedIndex();        
        idc.deleteFromListModel(n, clm);
    }//GEN-LAST:event_deleteCondButtonActionPerformed

    private void clearCondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCondButtonActionPerformed
        // TODO add your handling code here:
        idc.clearListModel(clm);
    }//GEN-LAST:event_clearCondButtonActionPerformed

    private void addCondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCondButtonActionPerformed
        // TODO add your handling code here:
        String text = newCondField.getText();
        if (!text.isEmpty()){            
            newCondField.setText("");
            idc.addToListModel(text, clm);
        }else{                           
           errorDialog.setTitle("Error");
           errorMessage.setText("No text introuced!");
           errorDialog.setVisible(true);
           errorDialog.pack();
        }         
    }//GEN-LAST:event_addCondButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
         dc.collectTableInfo(jTable1, condIndex);
         
        condIndex--;
        conditionLabel.setText(clm.get(condIndex).toString());
        
        jTable1 = dc.getTable(condIndex);
        jScrollPane1.setViewportView(jTable1);

        nextButton.setEnabled(true);
        finishButton.setEnabled(false);
        if (condIndex == 0){
            previousButton.setEnabled(false);
        }
        
    }//GEN-LAST:event_previousButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO add your handling code here:
        dc.collectTableInfo(jTable1, condIndex);
        ArrayList<Triple<String>> triples = dc.generateTriples();
        
        for (int k=0;k<triples.size();k++){
            System.out.println(triples.get(k).toString());
        }
        System.exit(0);
    }//GEN-LAST:event_finishButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        errorDialog.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
                
            InsertDialog.pack();
            InsertDialog.setVisible(true);
        
            //InsertDialog initialize
            olm.clear();
            alm.clear();
            clm.clear();
            objList.setModel(olm);
            attrList.setModel(alm);
            condList.setModel(clm);
            
            closeButton.setText("OK");
            errorDialog.dispose();        
    }//GEN-LAST:event_confirmButtonActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DataFrame().setVisible(true);
            }
        });
    }
    
    
//    private javax.swing.JTable jTable1; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog InsertDialog;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addAttrButton;
    private javax.swing.JButton addCondButton;
    private javax.swing.JButton addObjButton;
    private javax.swing.JList attrList;
    private javax.swing.JLabel attrListLabel;
    private javax.swing.JPanel attributesTab;
    private javax.swing.JButton clearAttrButton;
    private javax.swing.JButton clearCondButton;
    private javax.swing.JButton clearObjButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JList condList;
    private javax.swing.JLabel condListLabel;
    private javax.swing.JLabel conditionLabel;
    private javax.swing.JPanel conditionsTab;
    private javax.swing.JButton confirmButton;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JButton deleteAttrButton;
    private javax.swing.JButton deleteCondButton;
    private javax.swing.JButton deleteObjButton;
    private javax.swing.JMenuItem editCompMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton finishButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField newAttrField;
    private javax.swing.JLabel newAttrLabel;
    private javax.swing.JTextField newCondField;
    private javax.swing.JLabel newCondLabel;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JTextField newObjField;
    private javax.swing.JLabel newObjLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JList objList;
    private javax.swing.JLabel objListLabel;
    private javax.swing.JPanel objectsTab;
    private javax.swing.JButton okInsertButton;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton previousButton;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
    

}
