package ro.ubbcluj2013.cs;

import java.util.ArrayList;


/**
 * This is the class that handles importing data from the CSX file
 * that is generated by Elba. A CSX is written as an XML file that
 * contains graphical used by graph drawers
 */
public class ElbaCSXImporter {
	//Path to the CSX file
	private String csxFilePath;
	
	//Class that handles the parsing
	private CSXHandler_DOM csxHandler;
	
	
	//The resulted colected data:
	
	//The objects that we use further
	private ArrayList<CSXObject> csxObjectList;
	
	//The list of diagram names
	private ArrayList<String> diagramNameList;
	

	public ElbaCSXImporter(String _csxFilePath){
		this.csxFilePath = _csxFilePath;
		
		this.csxHandler = new CSXHandler_DOM( this.csxFilePath );
		
		this.csxObjectList = csxHandler.loadFromCSX();
		this.diagramNameList = csxHandler.getDiagramNameList();
	}
	
	

	//Getters and setters
	public String getCsxFilePath() {
		return csxFilePath;
	}

	public void setCsxFilePath(String csxFilePath) {
		this.csxFilePath = csxFilePath;
	}

	public ArrayList<CSXObject> getCsxObjectList() {
		return csxObjectList;
	}

	public void setCsxObjectList(ArrayList<CSXObject> csxObjectList) {
		this.csxObjectList = csxObjectList;
	}
	
	public ArrayList<String> getDiagramNameList() {
		return diagramNameList;
	}

	public void setDiagramNameList(ArrayList<String> diagramNameList) {
		this.diagramNameList = diagramNameList;
	}

}
